const emojis = [
    { id: 1, name: 'Sly Smirk', 
      gridSource: require('../assets/images/1.png'), 
      detailSource: require('../assets/images/1a.png'), 
      bgColor: '#005f46', btnColor: '#007d5c',
      description: "Hey there, caught your attention, huh? I'm the emoji of mischief and confidence. Perfect for those (I know something you don't) moments.\n\n When life gives you a cheeky idea, I’m your partner in crime! Add me to your conversations to bring a playful spark and leave people guessing. I radiate confidence but with a twist of sass, because who doesn’t love a bit of mystery?",
    },
    { id: 2, name: 'Puppy Eyes Bliss', 
      gridSource: require('../assets/images/2.png'), 
      detailSource: require('../assets/images/2a.png'), 
      bgColor: '#F48FB1', btnColor: '#f26897',
      description: "Don't you dare ignore me! I'm the ultimate weapon of cuteness and persuasion. Use me to melt hearts instantly.From winning arguments to guilt-tripping your friends in the cutest way, I’m here for you. \n\nThose big, innocent eyes say it all—(I’m too cute to resist!) Let me be your go-to for getting your way without saying a word.",
    },
    { id: 3, name: 'Cheeky Tongue Twister', 
      gridSource: require('../assets/images/3.png'), 
      detailSource: require('../assets/images/3a.png'), 
      bgColor: '#36B3E4', btnColor: '#10a9e6',
      description: "Yaaas, I'm all about fun and silliness! Let me add a dash of goofy charm to your texts. Life's too short to be serious. \n\n When you’re feeling quirky and mischievous, I’m the face to show it!\n\n Whether you’re teasing a friend or sharing a joke, I bring the fun energy that makes everyone smile. Stick your tongue out, and let’s get goofy together",
    },
    { id: 4, name: 'Starstruck Wonder', 
      gridSource: require('../assets/images/4.png'), 
      detailSource: require('../assets/images/4a.png'), 
      bgColor: '#FF7F50', btnColor: '#ff591c',
      description: "      WOW, you just left me starstruck! I’m your go-to emoji for excitement and admiration that’s out of this world.\n\n Use me when something is so amazing it leaves you speechless! I’m the perfect reaction to jaw-dropping moments, wild dreams, or when your favorite celebrity drops a surprise album. Keep the awe alive!",
    },
    { id: 5, name: 'Sassy Side-eye', 
      gridSource: require('../assets/images/5.png'), 
      detailSource: require('../assets/images/5a.png'), 
      bgColor: '#0D6EFD', btnColor: '#095cd6',
      description: " Really? That’s the best you’ve got? I’m the queen of subtle shade and sarcastic vibes.\n\nI don’t need words to make a point. Whether you’re throwing shade or reacting to something absurd, I’ve got your back. My side-eye glance is sharp enough to cut through any nonsense—handle with care!",
    },
    { id: 6, name: 'Lovey-Dovey Delight', 
      gridSource: require('../assets/images/6.png'), 
      detailSource: require('../assets/images/6a.png'), 
      bgColor: '#FFD700', btnColor: '#ad9202',
      description: "Ooooh, don’t I just bat my lashes perfectly? I bring a touch of flirty charm to any conversation.\n\n I’m the emoji of sweet compliments and playful moments. Whether you’re feeling extra cute or trying to charm someone, I’m the secret ingredient for adding irresistible charisma to your chats.",
    },
    { id: 7, name: 'Gleeful Grin', 
      gridSource: require('../assets/images/7.png'), 
      detailSource: require('../assets/images/7a.png'), 
      bgColor: '#198754', btnColor: '#00b47e',
      description: "Hehe, I’m all about happy vibes and goofy smiles! Use me when you can’t hold back the laughter.\n\nLife’s too funny to keep a straight face, so let’s giggle and grin together! I’m here to brighten your chats and remind you that laughter is the best medicine.",
    },
    { id: 8, name: 'Awkward Look', 
      gridSource: require('../assets/images/8.png'), 
      detailSource: require('../assets/images/8a.png'), 
      bgColor: '#FFCC00', btnColor: '#ad8b00',
      description: "Oops, did I just say that out loud? I’m your buddy for cringe-worthy moments and secondhand embarrassment.\n\n When the situation turns uncomfortable, I’m the emoji to call. My sideways glance says everything—“Please, someone save me from this awkwardness!”",
    },
    { id: 9, name: 'Love-Struck Eyes', 
      gridSource: require('../assets/images/9.png'), 
      detailSource: require('../assets/images/9a.png'), 
      bgColor: '#6A0DAD', btnColor: '#52018c',
      description: "Whoa, did you see that cutie? I’m the emoji of pure infatuation, guaranteed to show your hopeless romantic side.\n\n When your heart skips a beat, I’m here to express it. Whether it’s a crush, a delicious meal, or your favorite song, let me scream “I’m in love!” for you.",
    },
    { id: 10, name: 'Sick Day Blues', 
      gridSource: require('../assets/images/10.png'), 
      detailSource: require('../assets/images/10a.png'), 
      bgColor: '#CDA4DE', btnColor: '#ba69db',
      description: " Achoo! Feeling under the weather? I’m here to whine about your sore throat and fever in style. Use me to let your friends know you need soup and sympathy. \n\nWith my thermometer and droopy eyes, I’m the ultimate “I feel like garbage” emoji."
    },
    { id: 11, name: 'Giddy Goof', 
      gridSource: require('../assets/images/11.png'), 
      detailSource: require('../assets/images/11a.png'), 
      bgColor: '#FA80A5', btnColor: '#fc4980',
      description: "Yippee, let’s have some fun! I’m the emoji of over-the-top excitement and playful energy. \n\n Whether you’re thrilled about plans or just feeling hyper, I’m the face of pure joy. My wide eyes and goofy smile bring contagious happiness wherever I go.",
    },
    { id: 12, name: 'Chill Dude', 
      gridSource: require('../assets/images/12.jpg'), 
      detailSource: require('../assets/images/12a.png'), 
      bgColor: '#bd9069', btnColor: '#9c6536',
      description: "Yo, what’s up? I’m just vibing, half-asleep but totally aware. \n\nLife’s too short to stress—so let’s just chill and enjoy the ride!",
    },
    { id: 13, name: 'Nervous Nellie', 
      gridSource: require('../assets/images/13.png'), 
      detailSource: require('../assets/images/13a.png'), 
      bgColor: '#FBE747', btnColor: '#c4af04',
      description: "Uh-oh, I feel a little uneasy about this. I’m your emoji for awkward situations and shaky nerves.\n\n Sweaty palms? Check. Stomach in knots? Check. When the tension rises, I’m here to be your nervous companion.",
    },
    { id: 14, name: ' Quirky Quirk', 
      gridSource: require('../assets/images/14.png'), 
      detailSource: require('../assets/images/14a.png'), 
      bgColor: '#4898a8', btnColor: '#267f91',
      description: "Oops! I might have bitten off more than I can chew—don’t mind the tongue, it’s just how I roll in the land of silly",
    },
    { id: 15, name: 'Angry Eyebrows', 
      gridSource: require('../assets/images/15.png'), 
      detailSource: require('../assets/images/15a.png'), 
      bgColor: '#84868a', btnColor: '#747b87',
      description: "Grr, you don’t wanna mess with me! I’m the emoji of frustration, here to pack a punch of attitude.\n\n  When someone crosses the line, I step in with fiery intensity. Let me do the glaring while you cool off.",
    },
    { id: 16, name: 'Cheeky Wink', 
      gridSource: require('../assets/images/16.png'), 
      detailSource: require('../assets/images/16a.png'), 
      bgColor: '#A05DAE', btnColor: '#9f33b5',
      description: "Gotcha! I’m all about playful teasing and harmless pranks. Add me to spice up your convos. \n\n Whether you’re sharing a secret or cracking a joke, my wink adds that perfect hint of cheekiness and charm.",
    },
    { id: 17, name: 'Sad Soul', 
      gridSource: require('../assets/images/17.png'), 
      detailSource: require('../assets/images/17a.png'), 
      bgColor: '#3fb3fe', btnColor: '#16a1fa',
      description: "Sigh, just having one of those days. Let me help you share your blues and find some comfort.\n\n When the clouds roll in, I’m here to be your voice. Share your struggles, and let’s find the silver lining together.",
    },
    { id: 18, name: 'Startled Screech', 
      gridSource: require('../assets/images/18.png'), 
      detailSource: require('../assets/images/18a.png'), 
      bgColor: '#4c5ce9', btnColor: '#3a4ce8',
      description: "What in the world?! I’m the emoji for those jaw-dropping, mind-blowing moments.\n\nFrom shocking surprises to utter disbelief, my wide-open mouth says it all. Let’s gasp together!",
    },
    { id: 19, name: 'Calm Bliss', 
      gridSource: require('../assets/images/19.png'), 
      detailSource: require('../assets/images/19a.png'), 
      bgColor: '#fed713', btnColor: '#d9b500',
      description: "Shhh, relax. I’m the peaceful emoji, perfect for spreading serenity and zen vibes. \n\n Breathe in, breathe out. Whether you’re meditating or enjoying a quiet moment, I’m here to bring tranquility to your day.",
    },
    { id: 20, name: 'Wild Grin', 
      gridSource: require('../assets/images/20.png'), 
      detailSource: require('../assets/images/20a.png'), 
      bgColor: '#ff4530', btnColor: '#f71900',
      description: "Woohoo, let’s turn up the energy! I’m the emoji of uncontainable joy and unfiltered enthusiasm. \n\n When you’re ready to party, I’m your wingman. My vibrant",
    },
    { id: 21, name: 'Starry Blues', 
      gridSource: require('../assets/images/21.png'), 
      detailSource: require('../assets/images/21a.png'), 
      bgColor: '#d287e1', btnColor: '#c953e0',
      description: "Aww, did you just compliment me? I’m here to blush away with my charming blue stare. \n\n Whether you’re swooning or feeling shy, my glimmering eyes speak volumes. Let me capture those heartwarming moments for you.",
    },
    { id: 22, name: 'Cozy Glow', 
      gridSource: require('../assets/images/22.png'), 
      detailSource: require('../assets/images/22a.png'), 
      bgColor: '#f57e20', btnColor: '#f26c02',
      description: "Ahhh, let’s snuggle up and relax. I’m all about warm feelings and contentment. \n\n When the world feels right, I’m the emoji to share. Whether it’s cozy nights or heartfelt moments, I wrap your chats in warmth.",
    },
    { id: 23, name: 'Wacky Worry', 
      gridSource: require('../assets/images/23.png'), 
      detailSource: require('../assets/images/23a.png'), 
      bgColor: '#3faa49', btnColor: '#17a625',
      description: "Yikes, what just happened?! I’m the emoji of pure confusion and chaotic vibes.\n\n Life’s a mess sometimes, and I’m here to show it. With my swirling eyes and worried grin, I capture the whirlwind of emotions.",
    },
    { id: 24, name: 'Bubbly Delight', 
      gridSource: require('../assets/images/24.png'), 
      detailSource: require('../assets/images/24a.png'), 
      bgColor: '#bc49e8', btnColor: '#ad20e3',
      description: "Yay, everything is amazing! I’m the emoji for uncontainable happiness and cheerful expressions. \n\nLet’s celebrate every small win! My bubbly charm and radiant smile are perfect for spreading joy and positivity.",
    },
  ];
  
  export default emojis;
  